// This file is @generated by prost-build.
/// 价格线
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Line {
    /// 价格, 单位分
    #[prost(int32, tag = "1")]
    pub price: i32,
    /// 买入, 成交量, 单位股
    #[prost(double, tag = "2")]
    pub buy: f64,
    /// 卖出, 成交量, 单位股
    #[prost(double, tag = "3")]
    pub sell: f64,
}
/// 每日筹码分布统计
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Chips {
    /// 日期
    #[prost(string, tag = "1")]
    pub date: ::prost::alloc::string::String,
    /// 价格线
    #[prost(message, repeated, tag = "2")]
    pub dist: ::prost::alloc::vec::Vec<Line>,
}
/// 所有历史筹码分布的列表, 一天一条记录
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChipDistribution {
    #[prost(message, repeated, tag = "1")]
    pub list: ::prost::alloc::vec::Vec<Chips>,
}
