refresh_rate: 30 seconds
appenders:
  info_file:
    kind: file
    path: "logs/info.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {l} {m}{n}"
  error_file:
    kind: file
    path: "logs/error.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {l} {m}{n}"
  console:
    kind: console

root:
  level: info
  appenders:
    - console
    - info_file

loggers:
#  "":  # 根 logger 的补充配置
#    level: info
#    appenders:
#      - info_file
#    additive: false  # 不继承 root 的 appenders
  "error_logger":  # 单独处理 error 级别
    level: error
    appenders:
      - error_file
    additive: false