[package]
name = "stock"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44", features = ["full"] }
tokio-cron-scheduler = { version = "0.13" }
chrono = "0.4"
chrono-tz = "0.10"
lazy_static = "1.5.0"
ctor = "0.4"
anyhow = "1.0"
thiserror = "2.0"
regex = "1.11.1"
rayon = "1.10"

[profile.opt-dev]
inherits = "dev"
opt-level = 2

#[profile.test]  # 自定义测试的编译配置
#opt-level = 2   # 启用 O2 优化
#debug = false   # 禁用调试符号