// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: quant1x/proto/security_info.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SecurityType mirrors the SecurityType enum used in source code.
type SecurityType int32

const (
	SecurityType_SECURITY_TYPE_UNKNOWN   SecurityType = 0
	SecurityType_SECURITY_TYPE_STOCK     SecurityType = 1
	SecurityType_SECURITY_TYPE_ETF       SecurityType = 2
	SecurityType_SECURITY_TYPE_FUND      SecurityType = 3
	SecurityType_SECURITY_TYPE_BOND      SecurityType = 4
	SecurityType_SECURITY_TYPE_BSTOCK    SecurityType = 5
	SecurityType_SECURITY_TYPE_IPO       SecurityType = 6
	SecurityType_SECURITY_TYPE_INDEX     SecurityType = 7
	SecurityType_SECURITY_TYPE_BLOCK     SecurityType = 8
	SecurityType_SECURITY_TYPE_OPTION    SecurityType = 9
	SecurityType_SECURITY_TYPE_FUTURE    SecurityType = 10
	SecurityType_SECURITY_TYPE_WARRANT   SecurityType = 11
	SecurityType_SECURITY_TYPE_FOREX     SecurityType = 12
	SecurityType_SECURITY_TYPE_COMMODITY SecurityType = 13
	// Keep OTHER aligned to 255 to match existing code where Other = 255.
	SecurityType_SECURITY_TYPE_OTHER SecurityType = 255
)

// Enum value maps for SecurityType.
var (
	SecurityType_name = map[int32]string{
		0:   "SECURITY_TYPE_UNKNOWN",
		1:   "SECURITY_TYPE_STOCK",
		2:   "SECURITY_TYPE_ETF",
		3:   "SECURITY_TYPE_FUND",
		4:   "SECURITY_TYPE_BOND",
		5:   "SECURITY_TYPE_BSTOCK",
		6:   "SECURITY_TYPE_IPO",
		7:   "SECURITY_TYPE_INDEX",
		8:   "SECURITY_TYPE_BLOCK",
		9:   "SECURITY_TYPE_OPTION",
		10:  "SECURITY_TYPE_FUTURE",
		11:  "SECURITY_TYPE_WARRANT",
		12:  "SECURITY_TYPE_FOREX",
		13:  "SECURITY_TYPE_COMMODITY",
		255: "SECURITY_TYPE_OTHER",
	}
	SecurityType_value = map[string]int32{
		"SECURITY_TYPE_UNKNOWN":   0,
		"SECURITY_TYPE_STOCK":     1,
		"SECURITY_TYPE_ETF":       2,
		"SECURITY_TYPE_FUND":      3,
		"SECURITY_TYPE_BOND":      4,
		"SECURITY_TYPE_BSTOCK":    5,
		"SECURITY_TYPE_IPO":       6,
		"SECURITY_TYPE_INDEX":     7,
		"SECURITY_TYPE_BLOCK":     8,
		"SECURITY_TYPE_OPTION":    9,
		"SECURITY_TYPE_FUTURE":    10,
		"SECURITY_TYPE_WARRANT":   11,
		"SECURITY_TYPE_FOREX":     12,
		"SECURITY_TYPE_COMMODITY": 13,
		"SECURITY_TYPE_OTHER":     255,
	}
)

func (x SecurityType) Enum() *SecurityType {
	p := new(SecurityType)
	*p = x
	return p
}

func (x SecurityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecurityType) Descriptor() protoreflect.EnumDescriptor {
	return file_quant1x_proto_security_info_proto_enumTypes[0].Descriptor()
}

func (SecurityType) Type() protoreflect.EnumType {
	return &file_quant1x_proto_security_info_proto_enumTypes[0]
}

func (x SecurityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecurityType.Descriptor instead.
func (SecurityType) EnumDescriptor() ([]byte, []int) {
	return file_quant1x_proto_security_info_proto_rawDescGZIP(), []int{0}
}

// Exchange stores market identifiers used by DetectSecurity and related APIs.
type Exchange int32

const (
	// ExchangeIdShenZhen = 0
	Exchange_EXCHANGE_SHENZHEN Exchange = 0
	// ExchangeIdShangHai = 1
	Exchange_EXCHANGE_SHANGHAI Exchange = 1
	// ExchangeIdBeiJing = 2
	Exchange_EXCHANGE_BEIJING Exchange = 2
	// ExchangeIdHongKong = 21
	Exchange_EXCHANGE_HONGKONG Exchange = 21
	// ExchangeIdUSA = 22
	Exchange_EXCHANGE_USA Exchange = 22
	// Keep an explicit UNKNOWN/OTHER value aligned to 255 used in Go
	Exchange_EXCHANGE_OTHER Exchange = 255
)

// Enum value maps for Exchange.
var (
	Exchange_name = map[int32]string{
		0:   "EXCHANGE_SHENZHEN",
		1:   "EXCHANGE_SHANGHAI",
		2:   "EXCHANGE_BEIJING",
		21:  "EXCHANGE_HONGKONG",
		22:  "EXCHANGE_USA",
		255: "EXCHANGE_OTHER",
	}
	Exchange_value = map[string]int32{
		"EXCHANGE_SHENZHEN": 0,
		"EXCHANGE_SHANGHAI": 1,
		"EXCHANGE_BEIJING":  2,
		"EXCHANGE_HONGKONG": 21,
		"EXCHANGE_USA":      22,
		"EXCHANGE_OTHER":    255,
	}
)

func (x Exchange) Enum() *Exchange {
	p := new(Exchange)
	*p = x
	return p
}

func (x Exchange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Exchange) Descriptor() protoreflect.EnumDescriptor {
	return file_quant1x_proto_security_info_proto_enumTypes[1].Descriptor()
}

func (Exchange) Type() protoreflect.EnumType {
	return &file_quant1x_proto_security_info_proto_enumTypes[1]
}

func (x Exchange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Exchange.Descriptor instead.
func (Exchange) EnumDescriptor() ([]byte, []int) {
	return file_quant1x_proto_security_info_proto_rawDescGZIP(), []int{1}
}

// SecurityInfo is a compact, portable representation of a security's metadata.
type SecurityInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable unique identifier for the record (optional, e.g. "SSE:600519").
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Exchange-native code string (e.g. "600519", "000001", "00001").
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Market / exchange this code belongs to.
	Exchange Exchange `protobuf:"varint,3,opt,name=exchange,proto3,enum=quant1x.proto.Exchange" json:"exchange,omitempty"`
	// Security type, matches SecurityType enum above.
	Type SecurityType `protobuf:"varint,4,opt,name=type,proto3,enum=quant1x.proto.SecurityType" json:"type,omitempty"`
	// Short symbol/name usable in UIs or logs.
	Symbol string `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Full display name (primary locale).
	Name string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	// Short description or category.
	Desc string `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	// Note / provenance field — used to store authoritative comments.
	Note string `protobuf:"bytes,8,opt,name=note,proto3" json:"note,omitempty"`
	// Additional known aliases for the security (tickers, codes, etc.).
	Aliases []string `protobuf:"bytes,9,rep,name=aliases,proto3" json:"aliases,omitempty"`
	// ISO currency code, if applicable (e.g. "CNY", "HKD", "USD").
	Currency string `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`
	// Listing date when available.
	ListingDate *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=listing_date,json=listingDate,proto3" json:"listing_date,omitempty"`
	// Delisting flag and delist date when known.
	Delisted   bool                   `protobuf:"varint,12,opt,name=delisted,proto3" json:"delisted,omitempty"`
	DelistDate *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=delist_date,json=delistDate,proto3" json:"delist_date,omitempty"`
	// Issuer name or short identifier.
	Issuer string `protobuf:"bytes,14,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// Trading lot/board lot size (if applicable).
	LotSize uint32 `protobuf:"varint,15,opt,name=lot_size,json=lotSize,proto3" json:"lot_size,omitempty"`
	// Number of decimals used for prices/quoting (if relevant).
	Decimals uint32 `protobuf:"varint,16,opt,name=decimals,proto3" json:"decimals,omitempty"`
	// Optional standardized identifiers.
	Isin  string `protobuf:"bytes,17,opt,name=isin,proto3" json:"isin,omitempty"`
	Cusip string `protobuf:"bytes,18,opt,name=cusip,proto3" json:"cusip,omitempty"`
	// Free-form key/value map for extra, implementation-specific fields.
	Extra         map[string]string `protobuf:"bytes,19,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityInfo) Reset() {
	*x = SecurityInfo{}
	mi := &file_quant1x_proto_security_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityInfo) ProtoMessage() {}

func (x *SecurityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_quant1x_proto_security_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityInfo.ProtoReflect.Descriptor instead.
func (*SecurityInfo) Descriptor() ([]byte, []int) {
	return file_quant1x_proto_security_info_proto_rawDescGZIP(), []int{0}
}

func (x *SecurityInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecurityInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SecurityInfo) GetExchange() Exchange {
	if x != nil {
		return x.Exchange
	}
	return Exchange_EXCHANGE_SHENZHEN
}

func (x *SecurityInfo) GetType() SecurityType {
	if x != nil {
		return x.Type
	}
	return SecurityType_SECURITY_TYPE_UNKNOWN
}

func (x *SecurityInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SecurityInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecurityInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *SecurityInfo) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *SecurityInfo) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *SecurityInfo) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SecurityInfo) GetListingDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ListingDate
	}
	return nil
}

func (x *SecurityInfo) GetDelisted() bool {
	if x != nil {
		return x.Delisted
	}
	return false
}

func (x *SecurityInfo) GetDelistDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DelistDate
	}
	return nil
}

func (x *SecurityInfo) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *SecurityInfo) GetLotSize() uint32 {
	if x != nil {
		return x.LotSize
	}
	return 0
}

func (x *SecurityInfo) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *SecurityInfo) GetIsin() string {
	if x != nil {
		return x.Isin
	}
	return ""
}

func (x *SecurityInfo) GetCusip() string {
	if x != nil {
		return x.Cusip
	}
	return ""
}

func (x *SecurityInfo) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

var File_quant1x_proto_security_info_proto protoreflect.FileDescriptor

const file_quant1x_proto_security_info_proto_rawDesc = "" +
	"\n" +
	"!quant1x/proto/security_info.proto\x12\rquant1x.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x05\n" +
	"\fSecurityInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x123\n" +
	"\bexchange\x18\x03 \x01(\x0e2\x17.quant1x.proto.ExchangeR\bexchange\x12/\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1b.quant1x.proto.SecurityTypeR\x04type\x12\x16\n" +
	"\x06symbol\x18\x05 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\a \x01(\tR\x04desc\x12\x12\n" +
	"\x04note\x18\b \x01(\tR\x04note\x12\x18\n" +
	"\aaliases\x18\t \x03(\tR\aaliases\x12\x1a\n" +
	"\bcurrency\x18\n" +
	" \x01(\tR\bcurrency\x12=\n" +
	"\flisting_date\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vlistingDate\x12\x1a\n" +
	"\bdelisted\x18\f \x01(\bR\bdelisted\x12;\n" +
	"\vdelist_date\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"delistDate\x12\x16\n" +
	"\x06issuer\x18\x0e \x01(\tR\x06issuer\x12\x19\n" +
	"\blot_size\x18\x0f \x01(\rR\alotSize\x12\x1a\n" +
	"\bdecimals\x18\x10 \x01(\rR\bdecimals\x12\x12\n" +
	"\x04isin\x18\x11 \x01(\tR\x04isin\x12\x14\n" +
	"\x05cusip\x18\x12 \x01(\tR\x05cusip\x12<\n" +
	"\x05extra\x18\x13 \x03(\v2&.quant1x.proto.SecurityInfo.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x8b\x03\n" +
	"\fSecurityType\x12\x19\n" +
	"\x15SECURITY_TYPE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13SECURITY_TYPE_STOCK\x10\x01\x12\x15\n" +
	"\x11SECURITY_TYPE_ETF\x10\x02\x12\x16\n" +
	"\x12SECURITY_TYPE_FUND\x10\x03\x12\x16\n" +
	"\x12SECURITY_TYPE_BOND\x10\x04\x12\x18\n" +
	"\x14SECURITY_TYPE_BSTOCK\x10\x05\x12\x15\n" +
	"\x11SECURITY_TYPE_IPO\x10\x06\x12\x17\n" +
	"\x13SECURITY_TYPE_INDEX\x10\a\x12\x17\n" +
	"\x13SECURITY_TYPE_BLOCK\x10\b\x12\x18\n" +
	"\x14SECURITY_TYPE_OPTION\x10\t\x12\x18\n" +
	"\x14SECURITY_TYPE_FUTURE\x10\n" +
	"\x12\x19\n" +
	"\x15SECURITY_TYPE_WARRANT\x10\v\x12\x17\n" +
	"\x13SECURITY_TYPE_FOREX\x10\f\x12\x1b\n" +
	"\x17SECURITY_TYPE_COMMODITY\x10\r\x12\x18\n" +
	"\x13SECURITY_TYPE_OTHER\x10\xff\x01*\x8c\x01\n" +
	"\bExchange\x12\x15\n" +
	"\x11EXCHANGE_SHENZHEN\x10\x00\x12\x15\n" +
	"\x11EXCHANGE_SHANGHAI\x10\x01\x12\x14\n" +
	"\x10EXCHANGE_BEIJING\x10\x02\x12\x15\n" +
	"\x11EXCHANGE_HONGKONG\x10\x15\x12\x10\n" +
	"\fEXCHANGE_USA\x10\x16\x12\x13\n" +
	"\x0eEXCHANGE_OTHER\x10\xff\x01B(Z&github.com/quant1x/quant1x/proto;protob\x06proto3"

var (
	file_quant1x_proto_security_info_proto_rawDescOnce sync.Once
	file_quant1x_proto_security_info_proto_rawDescData []byte
)

func file_quant1x_proto_security_info_proto_rawDescGZIP() []byte {
	file_quant1x_proto_security_info_proto_rawDescOnce.Do(func() {
		file_quant1x_proto_security_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quant1x_proto_security_info_proto_rawDesc), len(file_quant1x_proto_security_info_proto_rawDesc)))
	})
	return file_quant1x_proto_security_info_proto_rawDescData
}

var file_quant1x_proto_security_info_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_quant1x_proto_security_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_quant1x_proto_security_info_proto_goTypes = []any{
	(SecurityType)(0),             // 0: quant1x.proto.SecurityType
	(Exchange)(0),                 // 1: quant1x.proto.Exchange
	(*SecurityInfo)(nil),          // 2: quant1x.proto.SecurityInfo
	nil,                           // 3: quant1x.proto.SecurityInfo.ExtraEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_quant1x_proto_security_info_proto_depIdxs = []int32{
	1, // 0: quant1x.proto.SecurityInfo.exchange:type_name -> quant1x.proto.Exchange
	0, // 1: quant1x.proto.SecurityInfo.type:type_name -> quant1x.proto.SecurityType
	4, // 2: quant1x.proto.SecurityInfo.listing_date:type_name -> google.protobuf.Timestamp
	4, // 3: quant1x.proto.SecurityInfo.delist_date:type_name -> google.protobuf.Timestamp
	3, // 4: quant1x.proto.SecurityInfo.extra:type_name -> quant1x.proto.SecurityInfo.ExtraEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_quant1x_proto_security_info_proto_init() }
func file_quant1x_proto_security_info_proto_init() {
	if File_quant1x_proto_security_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quant1x_proto_security_info_proto_rawDesc), len(file_quant1x_proto_security_info_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quant1x_proto_security_info_proto_goTypes,
		DependencyIndexes: file_quant1x_proto_security_info_proto_depIdxs,
		EnumInfos:         file_quant1x_proto_security_info_proto_enumTypes,
		MessageInfos:      file_quant1x_proto_security_info_proto_msgTypes,
	}.Build()
	File_quant1x_proto_security_info_proto = out.File
	file_quant1x_proto_security_info_proto_goTypes = nil
	file_quant1x_proto_security_info_proto_depIdxs = nil
}
