// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trans.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_trans_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_trans_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021011 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_trans_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_trans_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_trans_2eproto;
namespace datasets {
class TickTransaction;
struct TickTransactionDefaultTypeInternal;
extern TickTransactionDefaultTypeInternal _TickTransaction_default_instance_;
}  // namespace datasets
PROTOBUF_NAMESPACE_OPEN
template<> ::datasets::TickTransaction* Arena::CreateMaybeMessage<::datasets::TickTransaction>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace datasets {

// ===================================================================

class TickTransaction final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:datasets.TickTransaction) */ {
 public:
  inline TickTransaction() : TickTransaction(nullptr) {}
  ~TickTransaction() override;
  explicit PROTOBUF_CONSTEXPR TickTransaction(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TickTransaction(const TickTransaction& from);
  TickTransaction(TickTransaction&& from) noexcept
    : TickTransaction() {
    *this = ::std::move(from);
  }

  inline TickTransaction& operator=(const TickTransaction& from) {
    CopyFrom(from);
    return *this;
  }
  inline TickTransaction& operator=(TickTransaction&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TickTransaction& default_instance() {
    return *internal_default_instance();
  }
  static inline const TickTransaction* internal_default_instance() {
    return reinterpret_cast<const TickTransaction*>(
               &_TickTransaction_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TickTransaction& a, TickTransaction& b) {
    a.Swap(&b);
  }
  inline void Swap(TickTransaction* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TickTransaction* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TickTransaction* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TickTransaction>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TickTransaction& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TickTransaction& from) {
    TickTransaction::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TickTransaction* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "datasets.TickTransaction";
  }
  protected:
  explicit TickTransaction(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimeFieldNumber = 1,
    kPriceFieldNumber = 2,
    kVolFieldNumber = 3,
    kNumFieldNumber = 4,
    kAmountFieldNumber = 5,
    kBuyOrSellFieldNumber = 6,
  };
  // string time = 1;
  void clear_time();
  const std::string& time() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_time(ArgT0&& arg0, ArgT... args);
  std::string* mutable_time();
  PROTOBUF_NODISCARD std::string* release_time();
  void set_allocated_time(std::string* time);
  private:
  const std::string& _internal_time() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_time(const std::string& value);
  std::string* _internal_mutable_time();
  public:

  // double price = 2;
  void clear_price();
  double price() const;
  void set_price(double value);
  private:
  double _internal_price() const;
  void _internal_set_price(double value);
  public:

  // int64 vol = 3;
  void clear_vol();
  int64_t vol() const;
  void set_vol(int64_t value);
  private:
  int64_t _internal_vol() const;
  void _internal_set_vol(int64_t value);
  public:

  // int64 num = 4;
  void clear_num();
  int64_t num() const;
  void set_num(int64_t value);
  private:
  int64_t _internal_num() const;
  void _internal_set_num(int64_t value);
  public:

  // double amount = 5;
  void clear_amount();
  double amount() const;
  void set_amount(double value);
  private:
  double _internal_amount() const;
  void _internal_set_amount(double value);
  public:

  // int64 buy_or_sell = 6;
  void clear_buy_or_sell();
  int64_t buy_or_sell() const;
  void set_buy_or_sell(int64_t value);
  private:
  int64_t _internal_buy_or_sell() const;
  void _internal_set_buy_or_sell(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:datasets.TickTransaction)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr time_;
    double price_;
    int64_t vol_;
    int64_t num_;
    double amount_;
    int64_t buy_or_sell_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_trans_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TickTransaction

// string time = 1;
inline void TickTransaction::clear_time() {
  _impl_.time_.ClearToEmpty();
}
inline const std::string& TickTransaction::time() const {
  // @@protoc_insertion_point(field_get:datasets.TickTransaction.time)
  return _internal_time();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TickTransaction::set_time(ArgT0&& arg0, ArgT... args) {
 
 _impl_.time_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:datasets.TickTransaction.time)
}
inline std::string* TickTransaction::mutable_time() {
  std::string* _s = _internal_mutable_time();
  // @@protoc_insertion_point(field_mutable:datasets.TickTransaction.time)
  return _s;
}
inline const std::string& TickTransaction::_internal_time() const {
  return _impl_.time_.Get();
}
inline void TickTransaction::_internal_set_time(const std::string& value) {
  
  _impl_.time_.Set(value, GetArenaForAllocation());
}
inline std::string* TickTransaction::_internal_mutable_time() {
  
  return _impl_.time_.Mutable(GetArenaForAllocation());
}
inline std::string* TickTransaction::release_time() {
  // @@protoc_insertion_point(field_release:datasets.TickTransaction.time)
  return _impl_.time_.Release();
}
inline void TickTransaction::set_allocated_time(std::string* time) {
  if (time != nullptr) {
    
  } else {
    
  }
  _impl_.time_.SetAllocated(time, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.time_.IsDefault()) {
    _impl_.time_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:datasets.TickTransaction.time)
}

// double price = 2;
inline void TickTransaction::clear_price() {
  _impl_.price_ = 0;
}
inline double TickTransaction::_internal_price() const {
  return _impl_.price_;
}
inline double TickTransaction::price() const {
  // @@protoc_insertion_point(field_get:datasets.TickTransaction.price)
  return _internal_price();
}
inline void TickTransaction::_internal_set_price(double value) {
  
  _impl_.price_ = value;
}
inline void TickTransaction::set_price(double value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:datasets.TickTransaction.price)
}

// int64 vol = 3;
inline void TickTransaction::clear_vol() {
  _impl_.vol_ = int64_t{0};
}
inline int64_t TickTransaction::_internal_vol() const {
  return _impl_.vol_;
}
inline int64_t TickTransaction::vol() const {
  // @@protoc_insertion_point(field_get:datasets.TickTransaction.vol)
  return _internal_vol();
}
inline void TickTransaction::_internal_set_vol(int64_t value) {
  
  _impl_.vol_ = value;
}
inline void TickTransaction::set_vol(int64_t value) {
  _internal_set_vol(value);
  // @@protoc_insertion_point(field_set:datasets.TickTransaction.vol)
}

// int64 num = 4;
inline void TickTransaction::clear_num() {
  _impl_.num_ = int64_t{0};
}
inline int64_t TickTransaction::_internal_num() const {
  return _impl_.num_;
}
inline int64_t TickTransaction::num() const {
  // @@protoc_insertion_point(field_get:datasets.TickTransaction.num)
  return _internal_num();
}
inline void TickTransaction::_internal_set_num(int64_t value) {
  
  _impl_.num_ = value;
}
inline void TickTransaction::set_num(int64_t value) {
  _internal_set_num(value);
  // @@protoc_insertion_point(field_set:datasets.TickTransaction.num)
}

// double amount = 5;
inline void TickTransaction::clear_amount() {
  _impl_.amount_ = 0;
}
inline double TickTransaction::_internal_amount() const {
  return _impl_.amount_;
}
inline double TickTransaction::amount() const {
  // @@protoc_insertion_point(field_get:datasets.TickTransaction.amount)
  return _internal_amount();
}
inline void TickTransaction::_internal_set_amount(double value) {
  
  _impl_.amount_ = value;
}
inline void TickTransaction::set_amount(double value) {
  _internal_set_amount(value);
  // @@protoc_insertion_point(field_set:datasets.TickTransaction.amount)
}

// int64 buy_or_sell = 6;
inline void TickTransaction::clear_buy_or_sell() {
  _impl_.buy_or_sell_ = int64_t{0};
}
inline int64_t TickTransaction::_internal_buy_or_sell() const {
  return _impl_.buy_or_sell_;
}
inline int64_t TickTransaction::buy_or_sell() const {
  // @@protoc_insertion_point(field_get:datasets.TickTransaction.buy_or_sell)
  return _internal_buy_or_sell();
}
inline void TickTransaction::_internal_set_buy_or_sell(int64_t value) {
  
  _impl_.buy_or_sell_ = value;
}
inline void TickTransaction::set_buy_or_sell(int64_t value) {
  _internal_set_buy_or_sell(value);
  // @@protoc_insertion_point(field_set:datasets.TickTransaction.buy_or_sell)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace datasets

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_trans_2eproto
